[package]
   name = "ejdi"
   version = "0.0.1"
   description = ""
   standard = "17"

[compiler]
   clang = {option = "-Wall -Werror"}
   gcc   = {option = "-Wall -Werror"}

[[bin]]
   name = "ejdi"
   source = ["src/.*"]
