[package]
   name = "ejdi"
   version = "0.0.1"
   description = ""
   standard = "2a"

[compiler]
   clang = {option = "-Wall "}
   gcc   = {option = "-Wall "}
   msvc  = {option = "/MP"}

[[bin]]
   name = "ejdi"
   source = ["src/.*"]
